sign: 20230626_exp

path:
    base: 
    df: 
    datalist: 
    image: 
    result: 

general:
    datalist: 1
    fold: 4
    image_size: 224
    batch_size: 32
    valid_batch_size: 8
    num_workers: 4
    wandb_mode: online
    seed: 42

train:
    epoch: 200

inference:
    num_sampling: 1

model:
    name: VisionTransformer_Base16
    pretrained: True
    mcdropout: True
    dropout_ratio: 0.1
    dropout_ratio2: 0.1
    num_classes: 7

scheduler:
    name: CosineAnnealingLR
    t_max: 200
    t_0: 25
    min_lr: 0.00003

optimizer:
    name: Adam
    lr: 0.00005
    wd: 0.0001

criterion:
    name: Focal Loss
